### ISSUE TITLE
3.14 release

### ISSUE THREAD

**Issue by capital-G** [supercollider/supercollider#6579]
SuperCollider 3.13.0 was released in February of 2023 and since then we had some great additions, fixes and improvements which are probably useful to distribute them to a wider audience through an official release.

Having the [SuperCollider symposium](https://scsynth.org/t/supercollider-symposium-2025/9911) on 13-15 March 2025 labelled *The Future of SuperCollider*, I'd propose to use this event as an opportunity to release the next major version, which would be `3.14.0` :)

The time horizon is ambitious but the event is a great opportunity, and quoting @dyfer from https://github.com/supercollider/supercollider/issues/6547#issuecomment-2499303785

> [...]and then focus on working towards 3.14 sooner than later.

The main questions we should discuss

* [ ] When should we "seal-off" the develop branch for an RC?
* [ ] What open issues/PRs do you consider for to the next major release?
* [ ] Should we target the symposium date for an RC or for an actual major release? 

Feel free to add issues/PR to the milestone 3.14 (see https://github.com/supercollider/supercollider/milestone/25) or use this issue to discuss the scope of the next major release. I created a new GH project @ https://github.com/orgs/supercollider/projects/2/views/1 in order to obtain a better overview and will try to manage this according to the comments here and elsewhere - right now it is rather empty but this is about to change.

Also please state if you agree or disagree with the proposition of a mid-March release of 3.14.0 so we can get an overview within the dev-community about this.
It would be also great if you could state your capacities until March to see if we have enough capacity within the community for such an endeavor.

Also see https://github.com/supercollider/supercollider/wiki/Releasing-cycle-and-process for the formalities of a release (which suggests a major release every 3-6 months which seems long overdue)

**Comment by cdbzb** [comment]
I'll defer to more active folks but I think this would be *great* and I'd be happy to do at least some testing

**Comment by prko** [comment]
For me, it would be great if the following PRs and issues could be implemented:
- #6501
- #6401
- #6566
- #6563
- #6554
- #6549
- #6545
- #6537 
- #6536 
- #6534 
- #6479
A related issue seems to have been removed.... I cannot find some of my posts that belong to it.
- #6539
- #6415 
- #6409 
- #6406 
- #6394
- #6385 
- #6379
- #6369 
- #6371
- #6366
- #6315
- #6313
- #6312 
- #6294 
- #6291 
- #6283
- #6282 
- #6278 
- #6265
#6304
- #6207
- #6171
- #6168
- #6154
- #6153
- #6141
- #6136
- #6135
- #6046
- #6026

I would devote some time to achieving some of them...

**Comment by capital-G** [comment]
@prko regarding your comments from some PRs

> Could this PR be approved and merged before the 3.14 release?

I think this wouldn't be a problem but currently there are no exact plans for a 3.14 release. I suggested to do one for the SC symposium but as the social traction was rather reluctant I decided to not pursuit it further, but I'll try to bring this topic up again on the upcoming symposium.

Once there will be more concrete plannings for a 3.14 release we will fill https://github.com/orgs/supercollider/projects/2 which will include as much as possible from your suggested list (and beyond).

**Comment by prko** [comment]
>btw - please do not add merge commits to your PRs if they are not necessary as it adds noise to the PRs commit history. Merge commits are essentially only necessary when merging from a temporary feature branch into a stable branch (dev/main), feature branches (or PRs) don't need to be up-to-date with develop and should only be rebased if they tend to grow stale - i.e. merge conflicts or when manually requested by someone in order to verify some integrations before merging.

Thanks for the info.
I thought the branch should always be up-to-date.
I know rebase and have done it two or three times, but I preferred to update the branch because updating branches is easier than rebasing..... I will follow this and not update the branch unless there is a request from others. 

>I think this wouldn't be a problem but currently there are no exact plans for a 3.14 release. I suggested to do one for the SC symposium but as the social traction was rather reluctant I decided to not pursuit it further, but I'll try to bring this topic up again on the upcoming symposium.

OK, I was not aware of that either. It is not a problem! It is a bit unfortunate to hear that the 3.14 release will be delayed, but the good thing is that we do not have to rush to respond.

**Comment by capital-G** [comment]
To give some update on this from todays dev meeting:

3.14 will be a release w/o any changes to the Plugin API.
3.15 will follow soon afterwards and will contain changes to the Plugin API (i.e. #6145 ?! <3)

**Comment by capital-G** [comment]
**Updates after dev meeting 2025-04-22. Documentation issues are skipped b/c no one of the doc team was present.**

> [Text mirror issue in SC-IDE (`Attempted to modify missing Text Mirror for Document`) #6401](https://github.com/supercollider/supercollider/issues/6401)

Waiting for a PR - assigned to dyfer for testing out the fix in the comment

> [Add file tree widget to IDE #6549](https://github.com/supercollider/supercollider/pull/6549)

=> moved to 3.15

> * [ClassLib: ServerPlusGUI: plotTreeView rework #6545](https://github.com/supercollider/supercollider/pull/6545)

Elgiano will close this PR b/c its too complex - a new reworked PR will come at some point

> * [ClassLib: PlotView stepwise modes fix missing last step #6479](https://github.com/supercollider/supercollider/pull/6479)

Elgiano will take a look at this

> * [String literal size limit: Documentation and bugfix #6415](https://github.com/supercollider/supercollider/pull/6415)

Merged - another PR by Jordan will make this size configurable.

> * [ClassLib: fix Set.remove not returning the item #6409](https://github.com/supercollider/supercollider/pull/6409)

telephon will need to review/merge this

> * [add insertKeepSize and clipInsertKeepSize to ArrayedCollection and List #6394](https://github.com/supercollider/supercollider/pull/6394)

Jordan will review it

> * [The unimplemented methods of Pen, documented with examples, should be implemented. #6371](https://github.com/supercollider/supercollider/issues/6371)

Pushed back to 3.15

> * [CTRL + R does not invoke Find-Replace bar on the bottom of SC-IDE on Linux #6315](https://github.com/supercollider/supercollider/issues/6315)

Needs further inspection by simon - but elgiano can't reproduce it on arch w/ awesomewm - maybe this is a gnome/kde issue?

> * [Sync server volume between multiple clients #6313](https://github.com/supercollider/supercollider/pull/6313)

Waiting for review by scott.

> * [openOS behaviour on Windows #6312](https://github.com/supercollider/supercollider/issues/6312)

christof reproduced this - the problem seems strange/interesting - see https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/start

> * [add 'bounds' arg to `.plotTree`; make `.plotTree` a single instance window; add `ServerTreeView` class #6294](https://github.com/supercollider/supercollider/pull/6294)

dyfer left a comment - see also https://scsynth.org/t/node-tree-development/10447

>  * [Process.schelp: fix outdated incorrect explanation for `thisProcess.nowExecutingPath` with examples #6291](https://github.com/supercollider/supercollider/pull/6291)

Waiting for another PR.

> * [Add position arg to .meter to set s.meter position (width and height are automatically calculated) #6283](https://github.com/supercollider/supercollider/pull/6283)

part of rework of plot-tree - simon will take a look at this.

> * [added line numbers to code mirror of the help document #6207](https://github.com/supercollider/supercollider/pull/6207)

dennis will try to review this. 

> * [some text of SC-IDE for Windows is too small #6154](https://github.com/supercollider/supercollider/issues/6154)

dyfer will take a look at this
 
> * [Add `localIP`, `localEndPoint` and `localIPs` class methods to NetAddr #6153](https://github.com/supercollider/supercollider/pull/6153)

merged

> * [Help Browser navigation shortcuts only work on MacOS #6136](https://github.com/supercollider/supercollider/issues/6136)

Maybe this is linked to #6315 ?

> * [Adding .sortedCounts to Bag and .countStats to Collection #6046](https://github.com/supercollider/supercollider/issues/6046)

If a PR is merged by 2025-05-31 its in.

**Comment by capital-G** [comment]
@dyfer what is the procedure regarding the changelog?

**Comment by capital-G** [comment]
> I need to remember how I got just the list of PRs and start from there.

IIRC you get these via https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

> I'm down to do this on the call and split tasks. Let's coordinate time over DM.

👍

**Comment by dyfer** [comment]
> IIRC you get these via https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

Yes, I know, but how to I generate them BEFORE making the release?

**Comment by dyfer** [comment]
Ah yes! Then this is how I must've done it in the past. Thanks!

**Comment by capital-G** [comment]
As communicated in the forum chat, the deadline for all 3.14 PRs will be 2025-06-05 @ 19:00 CEST

**Comment by capital-G** [comment]
Checklist for 3.14-rc2 (feel free to edit)

* [x] Cherry pick https://github.com/supercollider/supercollider/pull/7025
* [x] Update CHANGELOG
* [x] Decide whether https://github.com/supercollider/supercollider/pull/7021#issuecomment-3031438444 should be part of 3.14 or 3.15
* [x] Fix standard theme color (increase contrast of success message)
* [x] Increase font size of status box to match 3.13

**Comment by dyfer** [comment]
3.14.0 is out! 🎉

I think we can close this now.

**Comment by dyfer** [comment]
I'll unpin this...
